# Generated by Django 4.2.7 on 2023-11-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='created_by',
        ),
    ]
