# Generated by Django 4.2.7 on 2023-11-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_rename_user_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='user',
        ),
    ]
