# Generated by Django 4.2.7 on 2023-11-27 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_rename_created_by_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_api.project')),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='project_api_id_937880_idx')],
            },
        ),
    ]
