# Generated by Django 4.2.7 on 2023-11-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_projectentry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectentry',
            name='project_api_id_937880_idx',
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='project_api.project'),
        ),
    ]
